# Generated by Django 3.0.5 on 2020-04-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('asset', models.CharField(max_length=20)),
                ('action', models.CharField(choices=[('call', 'Call'), ('put', 'Put')], max_length=10)),
                ('duration', models.IntegerField()),
                ('martingale', models.BooleanField(default=False)),
                ('martingale_factor', models.DecimalField(decimal_places=1, max_digits=2)),
                ('start_datetime', models.DateTimeField()),
            ],
        ),
    ]
